// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMP2kI-e2E1JRWH9HV3OhE-xTvavSOJtk',
    appId: '1:622179944339:web:98fb78987637b5a0668a66',
    messagingSenderId: '622179944339',
    projectId: 'lexit-ee622',
    authDomain: 'lexit-ee622.firebaseapp.com',
    storageBucket: 'lexit-ee622.appspot.com',
    measurementId: 'G-T7BN0BH5L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbtAt691KTd0Z8gqCuMkjMXY1BqKGZfoo',
    appId: '1:622179944339:android:86179cf64e46f7f1668a66',
    messagingSenderId: '622179944339',
    projectId: 'lexit-ee622',
    storageBucket: 'lexit-ee622.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT6cFkVbPD17PJgOI5UYjqsIgBX69HuhM',
    appId: '1:622179944339:ios:9811c815d6654ade668a66',
    messagingSenderId: '622179944339',
    projectId: 'lexit-ee622',
    storageBucket: 'lexit-ee622.appspot.com',
    iosClientId:
        '622179944339-jct5nlkba68bprj5i1k99g242v9pqhpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.lexit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT6cFkVbPD17PJgOI5UYjqsIgBX69HuhM',
    appId: '1:622179944339:ios:9811c815d6654ade668a66',
    messagingSenderId: '622179944339',
    projectId: 'lexit-ee622',
    storageBucket: 'lexit-ee622.appspot.com',
    iosClientId:
        '622179944339-jct5nlkba68bprj5i1k99g242v9pqhpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.lexit',
  );
}
